In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("Data/Extras/Final_2020_dataset.csv")
df

,Institute,Academic Program Name,Quota,Seat Type,Gender,Opening Rank,Closing Rank,State
0,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,OPEN,Gender-Neutral,8816,11238,Odisha
1,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,OPEN,Female-only (including Supernumerary),13312,15697,Odisha
2,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,OPEN (PwD),Gender-Neutral,254P,254P,Odisha
3,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,EWS,Gender-Neutral,1579,1779,Odisha
4,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,EWS,Female-only (including Supernumerary),2655,2819,Odisha
...,...,...,...,...,...,...,...,...
8788,North Eastern Regional Institute of Science an...,"Electrical Engineering (4 Years, Bachelor of T...",AI,EWS,Gender-Neutral,9515,9515,Arunachal Pradesh
8789,North Eastern Regional Institute of Science an...,Electronics and Communication Engineering (4 Y...,AI,OPEN,Gender-Neutral,23734,23734,Arunachal Pradesh
8790,North Eastern Regional Institute of Science an...,Electronics and Communication Engineering (4 Y...,AI,EWS,Gender-Neutral,10153,10153,Arunachal Pradesh
8791,North Eastern Regional Institute of Science an...,"Mechanical Engineering (4 Years, Bachelor of T...",AI,EWS,Gender-Neutral,9547,9547,Arunachal Pradesh
8792,North Eastern Regional Institute of Science an...,"Mechanical Engineering (4 Years, Bachelor of T...",AI,OBC-NCL,Gender-Neutral,19386,19386,Arunachal Pradesh

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8793 entries, 0 to 8792
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Institute              8793 non-null   object
 1   Academic Program Name  8793 non-null   object
 2   Quota                  8793 non-null   object
 3   Seat Type              8793 non-null   object
 4   Gender                 8793 non-null   object
 5   Opening Rank           8793 non-null   object
 6   Closing Rank           8793 non-null   object
 7   State                  8793 non-null   object
dtypes: object(8)
memory usage: 549.7+ KB

In [5]:
df["Institute"].unique()

array(['Indian Institute of Technology Bhubaneswar',
       'Indian Institute of Technology Bombay',
       'Indian Institute of Technology Mandi',
       'Indian Institute of Technology Delhi',
       'Indian Institute of Technology Indore',
       'Indian Institute of Technology Kharagpur',
       'Indian Institute of Technology Hyderabad',
       'Indian Institute of Technology Jodhpur',
       'Indian Institute of Technology Kanpur',
       'Indian Institute of Technology Madras',
       'Indian Institute of Technology Gandhinagar',
       'Indian Institute of Technology Patna',
       'Indian Institute of Technology Roorkee',
       'Indian Institute of Technology (ISM) Dhanbad',
       'Indian Institute of Technology Ropar',
       'Indian Institute of Technology (BHU) Varanasi',
       'Indian Institute of Technology Guwahati',
       'Indian Institute of Technology Bhilai',
       'Indian Institute of Technology Goa',
       'Indian Institute of Technology Palakkad',
       'Indian Institute of Technology Tirupati',
       'Indian Institute of Technology Jammu',
       'Indian Institute of Technology Dharwad',
       'Dr. B R Ambedkar National Institute of Technology, Jalandhar',
       'Malaviya National Institute of Technology Jaipur',
       'Maulana Azad National Institute of Technology Bhopal',
       'Motilal Nehru National Institute of Technology Allahabad',
       'National Institute of Technology Agartala',
       'National Institute of Technology Calicut',
       'National Institute of Technology Delhi',
       'National Institute of Technology Durgapur',
       'National Institute of Technology Goa',
       'National Institute of Technology Hamirpur',
       'National Institute of Technology Karnataka, Surathkal',
       'National Institute of Technology Meghalaya',
       'National Institute of Technology Nagaland',
       'National Institute of Technology Patna',
       'National Institute of Technology Puducherry',
       'National Institute of Technology Raipur',
       'National Institute of Technology Sikkim',
       'National Institute of Technology Arunachal Pradesh',
       'National Institute of Technology, Jamshedpur',
       'National Institute of Technology, Kurukshetra',
       'National Institute of Technology, Manipur',
       'National Institute of Technology, Mizoram',
       'National Institute of Technology, Rourkela',
       'National Institute of Technology, Silchar',
       'National Institute of Technology, Srinagar',
       'National Institute of Technology, Tiruchirappalli',
       'National Institute of Technology, Uttarakhand',
       'National Institute of Technology, Warangal',
       'Sardar Vallabhbhai National Institute of Technology, Surat',
       'Visvesvaraya National Institute of Technology, Nagpur',
       'National Institute of Technology, Andhra Pradesh',
       'Indian Institute of Engineering Science and Technology, Shibpur',
       'Atal Bihari Vajpayee Indian Institute of Information Technology & Management Gwalior',
       'Indian Institute of Information Technology (IIIT)Kota, Rajasthan',
       'Indian Institute of Information Technology Guwahati',
       'Indian Institute of Information Technology(IIIT) Kalyani, West Bengal',
       'Indian Institute of Information Technology(IIIT) Kilohrad, Sonepat, Haryana',
       'Indian Institute of Information Technology(IIIT) Una, Himachal Pradesh',
       'Indian Institute of Information Technology (IIIT), Sri City, Chittoor',
       'Indian Institute of Information Technology(IIIT), Vadodara, Gujrat',
       'Indian Institute of Information Technology, Allahabad',
       'Indian Institute of Information Technology, Design & Manufacturing, Kancheepuram',
       'Pt. Dwarka Prasad Mishra Indian Institute of Information Technology, Design & Manufacture Jabalpur',
       'Indian Institute of Information Technology Manipur',
       'Indian Institute of Information Technology Srirangam, Tiruchirappalli',
       'Indian Institute of Information Technology Lucknow',
       'Indian Institute of Information Technology(IIIT) Dharwad',
       'Indian Institute of Information Technology Design & Manufacturing Kurnool, Andhra Pradesh',
       'Indian Institute of Information Technology(IIIT) Kottayam',
       'Indian Institute of Information Technology (IIIT) Ranchi',
       'Indian Institute of Information Technology (IIIT) Nagpur',
       'Indian Institute of Information Technology (IIIT) Pune',
       'Indian Institute of Information Technology Bhagalpur',
       'Indian Institute of Information Technology Bhopal',
       'Indian Institute of Information Technology Surat',
       'Indian Institute of Information Technology, Agartala',
       'Indian institute of information technology, Raichur, Karnataka',
       'Indian Institute of Information Technology, Vadodara International Campus Diu (IIITVICD)',
       'Assam University, Silchar',
       'Birla Institute of Technology, Mesra, Ranchi',
       'Gurukula Kangri Vishwavidyalaya, Haridwar',
       'Indian Institute of Carpet Technology, Bhadohi',
       'Institute of Infrastructure, Technology, Research and Management-Ahmedabad',
       'Institute of Technology, Guru Ghasidas Vishwavidyalaya (A Central University), Bilaspur, (C.G.)',
       'J.K. Institute of Applied Physics & Technology, Department of Electronics & Communication, University of Allahabad- Allahabad',
       'National Institute of Electronics and Information Technology, Aurangabad (Maharashtra)',
       'National Institute of Foundry & Forge Technology, Hatia, Ranchi',
       'Sant Longowal Institute of Engineering and Technology',
       'Mizoram University, Aizawl',
       'School of Engineering, Tezpur University, Napaam, Tezpur',
       'School of Planning & Architecture, Bhopal',
       'School of Planning & Architecture, New Delhi',
       'School of Planning & Architecture: Vijayawada',
       'Shri Mata Vaishno Devi University, Katra, Jammu & Kashmir',
       'HNB Garhwal University Srinagar (Garhwal)',
       'International Institute of Information Technology, Naya Raipur',
       'University of Hyderabad',
       'Punjab Engineering College, Chandigarh',
       'Jawaharlal Nehru University, Delhi',
       'International Institute of Information Technology, Bhubaneswar',
       'Central institute of Technology Kokrajar, Assam',
       'Pondicherry Engineering College, Puducherry',
       'Ghani Khan Choudhary Institute of Engineering and Technology, Malda, West Bengal',
       'Central University of Rajasthan, Rajasthan',
       'National Institute of Food Technology Entrepreneurship and Management, Sonepat, Haryana',
       'lndian Institute of Food Processing Technology, Thanjavur, Tamil Naidu.',
       'North Eastern Regional Institute of Science and Technology, Nirjuli-791109 (Itanagar),Arunachal Pradesh'],
      dtype=object)

In [6]:
for i in df.columns:
    print(f"The number of unique values in {i} column is/are : {len(df[i].unique())}")
    print("\n")
    print(f"The unique values in {i} column is/are : {df[i].unique()}")
    print("\n")
    print(f"The value counts for each value in {i} column is/are :  \n{df[i].value_counts()}")
    print("\n")
    print(f"The number of missing values is/are : {df[i].isna().sum()}")
    print("\n\n")
    print("*"*100)
    print("\n\n")

The number of unique values in Institute column is/are : 110


The unique values in Institute column is/are : ['Indian Institute of Technology Bhubaneswar'
 'Indian Institute of Technology Bombay'
 'Indian Institute of Technology Mandi'
 'Indian Institute of Technology Delhi'
 'Indian Institute of Technology Indore'
 'Indian Institute of Technology Kharagpur'
 'Indian Institute of Technology Hyderabad'
 'Indian Institute of Technology Jodhpur'
 'Indian Institute of Technology Kanpur'
 'Indian Institute of Technology Madras'
 'Indian Institute of Technology Gandhinagar'
 'Indian Institute of Technology Patna'
 'Indian Institute of Technology Roorkee'
 'Indian Institute of Technology (ISM) Dhanbad'
 'Indian Institute of Technology Ropar'
 'Indian Institute of Technology (BHU) Varanasi'
 'Indian Institute of Technology Guwahati'
 'Indian Institute of Technology Bhilai'
 'Indian Institute of Technology Goa'
 'Indian Institute of Technology Palakkad'
 'Indian Institute of Technology Tirupati'
 'Indian Institute of Technology Jammu'
 'Indian Institute of Technology Dharwad'
 'Dr. B R Ambedkar National Institute of Technology, Jalandhar'
 'Malaviya National Institute of Technology Jaipur'
 'Maulana Azad National Institute of Technology Bhopal'
 'Motilal Nehru National Institute of Technology Allahabad'
 'National Institute of Technology Agartala'
 'National Institute of Technology Calicut'
 'National Institute of Technology Delhi'
 'National Institute of Technology Durgapur'
 'National Institute of Technology Goa'
 'National Institute of Technology Hamirpur'
 'National Institute of Technology Karnataka, Surathkal'
 'National Institute of Technology Meghalaya'
 'National Institute of Technology Nagaland'
 'National Institute of Technology Patna'
 'National Institute of Technology Puducherry'
 'National Institute of Technology Raipur'
 'National Institute of Technology Sikkim'
 'National Institute of Technology Arunachal Pradesh'
 'National Institute of Technology, Jamshedpur'
 'National Institute of Technology, Kurukshetra'
 'National Institute of Technology, Manipur'
 'National Institute of Technology, Mizoram'
 'National Institute of Technology, Rourkela'
 'National Institute of Technology, Silchar'
 'National Institute of Technology, Srinagar'
 'National Institute of Technology, Tiruchirappalli'
 'National Institute of Technology, Uttarakhand'
 'National Institute of Technology, Warangal'
 'Sardar Vallabhbhai National Institute of Technology, Surat'
 'Visvesvaraya National Institute of Technology, Nagpur'
 'National Institute of Technology, Andhra Pradesh'
 'Indian Institute of Engineering Science and Technology, Shibpur'
 'Atal Bihari Vajpayee Indian Institute of Information Technology & Management Gwalior'
 'Indian Institute of Information Technology (IIIT)Kota, Rajasthan'
 'Indian Institute of Information Technology Guwahati'
 'Indian Institute of Information Technology(IIIT) Kalyani, West Bengal'
 'Indian Institute of Information Technology(IIIT) Kilohrad, Sonepat, Haryana'
 'Indian Institute of Information Technology(IIIT) Una, Himachal Pradesh'
 'Indian Institute of Information Technology (IIIT), Sri City, Chittoor'
 'Indian Institute of Information Technology(IIIT), Vadodara, Gujrat'
 'Indian Institute of Information Technology, Allahabad'
 'Indian Institute of Information Technology, Design & Manufacturing, Kancheepuram'
 'Pt. Dwarka Prasad Mishra Indian Institute of Information Technology, Design & Manufacture Jabalpur'
 'Indian Institute of Information Technology Manipur'
 'Indian Institute of Information Technology Srirangam, Tiruchirappalli'
 'Indian Institute of Information Technology Lucknow'
 'Indian Institute of Information Technology(IIIT) Dharwad'
 'Indian Institute of Information Technology Design & Manufacturing Kurnool, Andhra Pradesh'
 'Indian Institute of Information Technology(IIIT) Kottayam'
 'Indian Institute of Information Technology (IIIT) Ranchi'
 'Indian Institute of Information Technology (IIIT) Nagpur'
 'Indian Institute of Information Technology (IIIT) Pune'
 'Indian Institute of Information Technology Bhagalpur'
 'Indian Institute of Information Technology Bhopal'
 'Indian Institute of Information Technology Surat'
 'Indian Institute of Information Technology, Agartala'
 'Indian institute of information technology, Raichur, Karnataka'
 'Indian Institute of Information Technology, Vadodara International Campus Diu (IIITVICD)'
 'Assam University, Silchar'
 'Birla Institute of Technology, Mesra, Ranchi'
 'Gurukula Kangri Vishwavidyalaya, Haridwar'
 'Indian Institute of Carpet Technology, Bhadohi'
 'Institute of Infrastructure, Technology, Research and Management-Ahmedabad'
 'Institute of Technology, Guru Ghasidas Vishwavidyalaya (A Central University), Bilaspur, (C.G.)'
 'J.K. Institute of Applied Physics & Technology, Department of Electronics & Communication, University of Allahabad- Allahabad'
 'National Institute of Electronics and Information Technology, Aurangabad (Maharashtra)'
 'National Institute of Foundry & Forge Technology, Hatia, Ranchi'
 'Sant Longowal Institute of Engineering and Technology'
 'Mizoram University, Aizawl'
 'School of Engineering, Tezpur University, Napaam, Tezpur'
 'School of Planning & Architecture, Bhopal'
 'School of Planning & Architecture, New Delhi'
 'School of Planning & Architecture: Vijayawada'
 'Shri Mata Vaishno Devi University, Katra, Jammu & Kashmir'
 'HNB Garhwal University Srinagar (Garhwal)'
 'International Institute of Information Technology, Naya Raipur'
 'University of Hyderabad' 'Punjab Engineering College, Chandigarh'
 'Jawaharlal Nehru University, Delhi'
 'International Institute of Information Technology, Bhubaneswar'
 'Central institute of Technology Kokrajar, Assam'
 'Pondicherry Engineering College, Puducherry'
 'Ghani Khan Choudhary Institute of Engineering and Technology, Malda, West Bengal'
 'Central University of Rajasthan, Rajasthan'
 'National Institute of Food Technology Entrepreneurship and Management, Sonepat, Haryana'
 'lndian Institute of Food Processing Technology, Thanjavur, Tamil Naidu.'
 'North Eastern Regional Institute of Science and Technology, Nirjuli-791109 (Itanagar),Arunachal Pradesh']


The value counts for each value in Institute column is/are :
Indian Institute of Technology Kharagpur                                                   384
National Institute of Technology, Rourkela                                                 359
National Institute of Technology Raipur                                                    251
Indian Institute of Technology (BHU) Varanasi                                              244
National Institute of Technology Hamirpur                                                  242
                                                                                          ...
Indian Institute of Information Technology(IIIT) Kalyani, West Bengal                        6
lndian Institute of Food Processing Technology, Thanjavur, Tamil Naidu.                      6
National Institute of Food Technology Entrepreneurship and Management, Sonepat, Haryana      5
Indian Institute of Information Technology, Agartala                                         5
Indian Institute of Carpet Technology, Bhadohi                                               5
Name: Institute, Length: 110, dtype: int64


The number of missing values is/are : 0



****************************************************************************************************



The number of unique values in Academic Program Name column is/are : 153


The unique values in Academic Program Name column is/are : ['Civil Engineering (4 Years, Bachelor of Technology)'
 'Civil Engineering and M. Tech. in Structural Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))'
 'Civil Engineering and M.Tech in Transportation Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))'
 'Civil Engineering and M.Tech. in Environmental Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))'
 'Computer Science and Engineering (4 Years, Bachelor of Technology)'
 'Computer Science and Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))'
 'Electrical Engineering and M.Tech Power Electronics and Drives (5 Years, Bachelor and Master of Technology (Dual Degree))'
 'Electrical Engineering (4 Years, Bachelor of Technology)'
 'Electronics and Communication Engineering (4 Years, Bachelor of Technology)'
 'Mechanical Engineering (4 Years, Bachelor of Technology)'
 'Mechanical Engineering and M. Tech. in Mechanical System Design (5 Years, Bachelor and Master of Technology (Dual Degree))'
 'Mechanical Engineering and M. Tech. in Thermal Science & Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))'
 'Mechanical Engineering with M.Tech. in Manufacturing Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))'
 'Metallurgical and Materials Engineering (4 Years, Bachelor of Technology)'
 'Metallurgical and Materials Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))'
 'Aerospace Engineering (4 Years, Bachelor of Technology)'
 'BS in Mathematics (4 Years, Bachelor of Science)'
 'Chemical Engineering (4 Years, Bachelor of Technology)'
 'Chemistry (4 Years, Bachelor of Science)'
 'Economics (4 Years, Bachelor of Science)'
 'Electrical Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))'
 'Energy Engineering with M.Tech. in Energy Systems Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))'
 'Engineering Physics (4 Years, Bachelor of Technology)'
 'Environmental Science and Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))'
 'Mechanical Engineering and M.Tech. in Computer Integrated Manufacturing (5 Years, Bachelor and Master of Technology (Dual Degree))'
 'Metallurgical Engineering & Materials Science (5 Years, Bachelor and Master of Technology (Dual Degree))'
 'Metallurgical Engineering and Materials Science (4 Years, Bachelor of Technology)'
 'Bio Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))'
 'Data Science and Engineering (4 Years, Bachelor of Technology)'
 'Biotechnology and Biochemical Engineering (4 Years, Bachelor of Technology)'
 'Chemical Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))'
 'Electrical Engineering (Power and Automation) (4 Years, Bachelor of Technology)'
 'Engineering and Computational Mechanics (4 Years, Bachelor of Technology)'
 'Materials Engineering (4 Years, Bachelor of Technology)'
 'Mathematics and Computing (4 Years, Bachelor of Technology)'
 'Mathematics and Computing (5 Years, Bachelor and Master of Technology (Dual Degree))'
 'Production and Industrial Engineering (4 Years, Bachelor of Technology)'
 'Textile Technology (4 Years, Bachelor of Technology)'
 'Aerospace Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))'
 'Agricultural and Food Engineering (4 Years, Bachelor of Technology)'
 'Agricultural and Food Engineering with M.Tech. in any of the listed specializations (5 Years, Bachelor and Master of Technology (Dual Degree))'
 'Applied Geology (5 Years, Integrated Master of Science)'
 'Architecture (5 Years, Bachelor of Architecture)'
 'Biotechnology and Biochemical Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))'
 'Chemistry (5 Years, Integrated Master of Science)'
 'Civil Engineering with any of the listed specialization (5 Years, Bachelor and Master of Technology (Dual Degree))'
 'Economics (5 Years, Integrated Master of Science)'
 'Electrical Engineering with M.Tech. in any of the listed specializations (5 Years, Bachelor and Master of Technology (Dual Degree))'
 'Electronics and Electrical Communication Engineering (4 Years, Bachelor of Technology)'
 'Electronics and Electrical Communication Engineering with M.Tech. in any of the listed specializations (5 Years, Bachelor and Master of Technology (Dual Degree))'
 'Exploration Geophysics (5 Years, Integrated Master of Science)'
 'Industrial and Systems Engineering (4 Years, Bachelor of Technology)'
 'Industrial and Systems Engineering with M.Tech. in Industrial and Systems Engineering and Management (5 Years, Bachelor and Master of Technology (Dual Degree))'
 'Instrumentation Engineering (4 Years, Bachelor of Technology)'
 'Manufacturing Science and Engineering (4 Years, Bachelor of Technology)'
 'Manufacturing Science and Engineering with M.Tech. in Industrial and Systems Engineering and Management (5 Years, Bachelor and Master of Technology (Dual Degree))'
 'Mathematics and Computing (5 Years, Integrated Master of Science)'
 'Mechanical Engineering with M.Tech. in any of the listed specializations (5 Years, Bachelor and Master of Technology (Dual Degree))'
 'Mining Engineering (4 Years, Bachelor of Technology)'
 'Mining Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))'
 'Mining Safety Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))'
 'Ocean Engineering and Naval Architecture (4 Years, Bachelor of Technology)'
 'Ocean Engineering and Naval Architecture (5 Years, Bachelor and Master of Technology (Dual Degree))'
 'Physics (5 Years, Integrated Master of Science)'
 'Quality Engineering Design and Manufacturing (5 Years, Bachelor and Master of Technology (Dual Degree))'
 'Artiﬁcial Intelligence (4 Years, Bachelor of Technology)'
 'Biomedical Engineering (4 Years, Bachelor of Technology)'
 'Engineering Science (4 Years, Bachelor of Technology)'
 'Materials Science and Metallurgical Engineering (4 Years, Bachelor of Technology)'
 'Artiﬁcial Intelligence and Data Science (4 Years, Bachelor of Technology)'
 'Bio Engineering (4 Years, Bachelor of Technology)'
 'Civil and Infrastructure Engineering (4 Years, Bachelor of Technology)'
 'Biological Sciences and Bioengineering (4 Years, Bachelor of Technology)'
 'Earth Sciences (4 Years, Bachelor of Science)'
 'Materials Science and Engineering (4 Years, Bachelor of Technology)'
 'Mathematics and Scientiﬁc Computing (4 Years, Bachelor of Science)'
 'Physics (4 Years, Bachelor of Science)'
 'Biological Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))'
 'Biological Sciences (5 Years, Bachelor of Science and Master of Science (Dual Degree))'
 'Engineering Design (5 Years, Bachelor and Master of Technology (Dual Degree))'
 'Naval Architecture and Ocean Engineering (4 Years, Bachelor of Technology)'
 'Physics (5 Years, Bachelor of Science and Master of Science (Dual Degree))'
 'Electrical and Electronics Engineering (4 Years, Bachelor of Technology)'
 'Applied Mathematics (5 Years, Integrated Master of Science)'
 'Bio Technology (4 Years, Bachelor of Technology)'
 'Geological Technology (5 Years, Integrated Master of Technology)'
 'Geophysical Technology (5 Years, Integrated Master of Technology)'
 'Polymer Science and Engineering (4 Years, Bachelor of Technology)'
 'Applied Geology (5 Years, Integrated Master of Technology)'
 'Applied Geophysics (5 Years, Integrated Master of Technology)'
 'Environmental Engineering (4 Years, Bachelor of Technology)'
 'Mathematics and Computing (5 Years, Integrated Master of Technology)'
 'Mineral and Metallurgical Engineering (4 Years, Bachelor of Technology)'
 'Mining Machinery Engineering (4 Years, Bachelor of Technology)'
 'Petroleum Engineering (4 Years, Bachelor of Technology)'
 'Biochemical Engineering with M.Tech. in Biochemical Engineering and Biotechnology (5 Years, Bachelor and Master of Technology (Dual Degree))'
 'Bioengineering with M.Tech in Biomedical Technology (5 Years, Bachelor and Master of Technology (Dual Degree))'
 'Ceramic Engineering (4 Years, Bachelor of Technology)'
 'Ceramic Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))'
 'Civil Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))'
 'Electrical Engineering with M.Tech. in Power Electronics (5 Years, Bachelor and Master of Technology (Dual Degree))'
 'Electronics Engineering (4 Years, Bachelor of Technology)'
 'Engineering Physics (5 Years, Bachelor and Master of Technology (Dual Degree))'
 'Industrial Chemistry (5 Years, Bachelor and Master of Technology (Dual Degree))'
 'Materials Science and Technology (5 Years, Bachelor and Master of Technology (Dual Degree))'
 'Mechanical Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))'
 'Metallurgical Engineering (4 Years, Bachelor of Technology)'
 'Metallurgical Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))'
 'Pharmaceutical Engineering & Technology (4 Years, Bachelor of Technology)'
 'Pharmaceutical Engineering & Technology (5 Years, Bachelor and Master of Technology (Dual Degree))'
 'Biosciences and Bioengineering (4 Years, Bachelor of Technology)'
 'Chemical Science and Technology (4 Years, Bachelor of Technology)'
 'Electronics and Electrical Engineering (4 Years, Bachelor of Technology)'
 'Data Science and Artiﬁcial Intelligence (4 Years, Bachelor of Technology)'
 'Industrial and Production Engineering (4 Years, Bachelor of Technology)'
 'Information Technology (4 Years, Bachelor of Technology)'
 'Instrumentation and Control Engineering (4 Years, Bachelor of Technology)'
 'Planning (4 Years, Bachelor of Planning)'
 'Chemistry (5 Years, Bachelor of Science and Master of Science (Dual Degree))'
 'Electronics and Instrumentation Engineering (4 Years, Bachelor of Technology)'
 'Mathematics & Computing (5 Years, Bachelor of Science and Master of Science (Dual Degree))'
 'Production Engineering (4 Years, Bachelor of Technology)'
 'Biotechnology (5 Years, Bachelor and Master of Technology (Dual Degree))'
 'Electronics and Communication Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))'
 'Bio Medical Engineering (4 Years, Bachelor of Technology)'
 'Computer Engineering (4 Years, Bachelor of Technology)'
 'Ceramic Engineering and M.Tech Industrial Ceramic (5 Years, Bachelor and Master of Technology (Dual Degree))'
 'Food Process Engineering (4 Years, Bachelor of Technology)'
 'Industrial Design (4 Years, Bachelor of Technology)'
 'Life Science (5 Years, Integrated Master of Science)'
 'Mathematics (5 Years, Integrated Master of Science)'
 'Integrated B. Tech.(IT) and M. Tech (IT) (5 Years, Integrated B. Tech. and M. Tech. /MBA)'
 'Integrated B. Tech.(IT) and MBA (5 Years, Integrated B. Tech. and M. Tech. /MBA)'
 'Information Technology-Business Informatics (4 Years, Bachelor of Technology)'
 'Smart Manufacturing (4 Years, Bachelor of Technology)'
 'Computer Science (4 Years, Bachelor of Technology)'
 'Computer Science and Artiﬁcial Intelligence (4 Years, Bachelor of Technology)'
 'Electronics and Communication Engineering with specialization in Design and Manufacturing (4 Years, Bachelor of Technology)'
 'Mechanical Engineering with specialization in Design and Manufacturing (4 Years, Bachelor of Technology)'
 'Mechatronics Engineering (4 Years, Bachelor of Technology)'
 'Agricultural Engineering (4 Years, Bachelor of Technology)'
 'Chemical Engineering (Plastic and Polymer) (4 Years, Bachelor of Technology)'
 'Carpet and Textile Technology (4 Years, Bachelor of Technology)'
 'Electronics System Engineering (4 Years, Bachelor of Technology)'
 'Metallurgy and Materials Engineering (4 Years, Bachelor of Technology)'
 'Food Technology (4 Years, Bachelor of Technology)'
 'Food Engineering and Technology (4 Years, Bachelor of Technology)'
 'Electrical and Instrumentation Engineering (4 Years, Bachelor of Technology)'
 'Computer Science (5 Years, Integrated Master of Technology)'
 'Computer Science & Engineering (5 Years, B.Tech. + M.Tech./MS (Dual Degree))'
 'Electronics & Communication Engineering (5 Years, B.Tech.+ M.Tech./MS (Dual Degree))'
 'Electronics and Telecommunication Engineering (4 Years, Bachelor of Technology)'
 'Food Technology and Management (4 Years, Bachelor of Technology)']



In [7]:
college_sorter = ['Indian Institute of Technology Madras' ,
                  'Indian Institute of Technology Delhi' ,
                  'Indian Institute of Technology Bombay' ,
                  'Indian Institute of Technology Kanpur' ,                  
                  'Indian Institute of Technology Kharagpur' ,
                  'Indian Institute of Technology Roorkee' ,
                  'Indian Institute of Technology Guwahati' ,
                  'Jawaharlal Nehru University, Delhi' , 
                  'University of Hyderabad' ,
                  'Indian Institute of Technology Hyderabad' , 
                  'National Institute of Technology, Tiruchirappalli' ,
                  'Indian Institute of Technology Indore' ,
                  'Indian Institute of Technology (BHU) Varanasi' ,
                  'Indian Institute of Technology (ISM) Dhanbad' ,
                  'National Institute of Technology Karnataka, Surathkal' ,
                  'National Institute of Technology, Rourkela' ,
                  'National Institute of Technology, Warangal' ,
                  'Indian Institute of Engineering Science and Technology, Shibpur' ,
                  'Indian Institute of Technology Bhubaneswar' ,
                  'National Institute of Technology Calicut' ,
                  'Indian Institute of Technology Gandhinagar' , 
                  'Indian Institute of Technology Ropar' ,                  
                  'Indian Institute of Technology Patna' , 
                  'Visvesvaraya National Institute of Technology, Nagpur' ,
                  'Indian Institute of Technology Mandi' ,
                  'School of Engineering, Tezpur University, Napaam, Tezpur' ,
                  'Malaviya National Institute of Technology Jaipur' ,
                  'Birla Institute of Technology, Mesra, Ranchi' ,
                  'National Institute of Technology, Kurukshetra' ,
                  'National Institute of Technology, Silchar' ,
                  'National Institute of Technology Durgapur' ,
                  'Motilal Nehru National Institute of Technology Allahabad' ,
                  'Dr. B R Ambedkar National Institute of Technology, Jalandhar' , 
                  'Indian Institute of Technology Jodhpur' , 
                  'Sardar Vallabhbhai National Institute of Technology, Surat' ,
                  'National Institute of Technology Meghalaya' ,
                  'Maulana Azad National Institute of Technology Bhopal' ,
                  'Indian Institute of Information Technology Guwahati' ,
                  'National Institute of Technology Raipur' ,
                  'Punjab Engineering College, Chandigarh' ,
                  'National Institute of Technology Agartala' ,
                  'National Institute of Technology Goa' ,
                  'National Institute of Technology, Jamshedpur' ,
                  'Pt. Dwarka Prasad Mishra Indian Institute of Information Technology, Design & Manufacture Jabalpur' ,
                  'National Institute of Technology Patna' ,
                  'National Institute of Technology Hamirpur' ,
                  'Indian Institute of Technology Tirupati',
                  'Indian Institute of Technology Palakkad' , 
                  'Indian Institute of Technology Bhilai' , 
                  'Indian Institute of Technology Goa' , 
                  'Indian Institute of Technology Jammu' , 
                  'Indian Institute of Technology Dharwad' , 
                  'Atal Bihari Vajpayee Indian Institute of Information Technology & Management Gwalior' ,
                  'Indian Institute of Information Technology, Allahabad' ,
                  'Pondicherry Engineering College, Puducherry' ,
                  'National Institute of Technology Puducherry' ,
                  'National Institute of Technology, Manipur' ,
                  'Indian Institute of Information Technology, Design & Manufacturing, Kancheepuram' ,
                  'National Institute of Technology Arunachal Pradesh' ,
                  'National Institute of Technology, Srinagar' ,
                  'National Institute of Technology Delhi' , 'National Institute of Technology, Mizoram' ,
                  'National Institute of Technology Nagaland' ,
                  'National Institute of Technology Sikkim' ,
                  'National Institute of Technology, Uttarakhand' ,
                  'National Institute of Technology, Andhra Pradesh' ,
                  'Indian Institute of Information Technology (IIIT) Pune' ,
                  'Indian Institute of Information Technology (IIIT)Kota, Rajasthan' ,
                  'Indian Institute of Information Technology (IIIT), Sri City, Chittoor' ,
                  'Indian Institute of Information Technology(IIIT), Vadodara, Gujrat' ,
                  'Indian Institute of Information Technology, Vadodara International Campus Diu (IIITVICD)',
                  'Indian Institute of Information Technology (IIIT) Nagpur' ,
                  'Indian Institute of Information Technology(IIIT) Kalyani, West Bengal' ,
                  'Indian Institute of Information Technology Lucknow' ,
                  'Indian Institute of Information Technology(IIIT) Dharwad' ,
                  'Indian Institute of Information Technology Bhagalpur' , 
                  'Indian Institute of Information Technology Bhopal' ,
                  'Indian Institute of Information Technology(IIIT) Kottayam' , 
                  'Indian Institute of Information Technology (IIIT) Ranchi' ,
                  'Indian Institute of Information Technology Surat' ,
                  'Indian Institute of Information Technology Manipur' ,
                  'Indian Institute of Information Technology Design & Manufacturing Kurnool, Andhra Pradesh' ,
                  'Indian Institute of Information Technology Srirangam, Tiruchirappalli' ,
                  'Indian Institute of Information Technology(IIIT) Kilohrad, Sonepat, Haryana' ,
                  'Indian Institute of Information Technology, Agartala' ,
                  'Indian institute of information technology, Raichur, Karnataka' ,
                  'Indian Institute of Information Technology(IIIT) Una, Himachal Pradesh' ,
                  'Assam University, Silchar' ,
                  'Gurukula Kangri Vishwavidyalaya, Haridwar' ,
                  'Indian Institute of Carpet Technology, Bhadohi' ,
                  'Institute of Infrastructure, Technology, Research and Management-Ahmedabad' ,
                  'Institute of Technology, Guru Ghasidas Vishwavidyalaya (A Central University), Bilaspur, (C.G.)' ,
                  'J.K. Institute of Applied Physics & Technology, Department of Electronics & Communication, University of Allahabad- Allahabad' ,
                  'National Institute of Electronics and Information Technology, Aurangabad (Maharashtra)' ,
                  'National Institute of Foundry & Forge Technology, Hatia, Ranchi' ,
                  'Sant Longowal Institute of Engineering and Technology' ,
                  'Mizoram University, Aizawl' ,
                  'School of Planning & Architecture, Bhopal' ,
                  'School of Planning & Architecture, New Delhi' ,
                  'School of Planning & Architecture: Vijayawada' ,
                  'Shri Mata Vaishno Devi University, Katra, Jammu & Kashmir' ,
                  'HNB Garhwal University Srinagar (Garhwal)' ,
                  'International Institute of Information Technology, Naya Raipur' ,
                  'International Institute of Information Technology, Bhubaneswar' ,
                  'Central institute of Technology Kokrajar, Assam' ,
                  'Ghani Khan Choudhary Institute of Engineering and Technology, Malda, West Bengal' ,
                  'Central University of Rajasthan, Rajasthan' ,
                  'National Institute of Food Technology Entrepreneurship and Management, Sonepat, Haryana' ,
                  'lndian Institute of Food Processing Technology, Thanjavur, Tamil Naidu.' ,
                  'North Eastern Regional Institute of Science and Technology, Nirjuli-791109 (Itanagar),Arunachal Pradesh']

In [8]:
for i in college_sorter :
    st = df["State"].loc[df["Institute"] == i].unique()[0]
    print(f"{i:50} -- {st}")

Indian Institute of Technology Madras              -- Tamil Nadu
Indian Institute of Technology Delhi               -- Delhi
Indian Institute of Technology Bombay              -- Maharashtra
Indian Institute of Technology Kanpur              -- Uttar Pradesh
Indian Institute of Technology Kharagpur           -- West Bengal
Indian Institute of Technology Roorkee             -- Uttarakhand
Indian Institute of Technology Guwahati            -- West Bengal
Jawaharlal Nehru University, Delhi                 -- Delhi
University of Hyderabad                            -- Telangana
Indian Institute of Technology Hyderabad           -- Telangana
National Institute of Technology, Tiruchirappalli  -- Tamil Nadu
Indian Institute of Technology Indore              -- Madhya Pradesh
Indian Institute of Technology (BHU) Varanasi      -- Uttar Pradesh
Indian Institute of Technology (ISM) Dhanbad       -- Jharkhand
National Institute of Technology Karnataka, Surathkal -- Karnataka
National Institute of Technology, Rourkela         -- Odisha
National Institute of Technology, Warangal         -- Telangana
Indian Institute of Engineering Science and Technology, Shibpur -- West Bengal
Indian Institute of Technology Bhubaneswar         -- Odisha
National Institute of Technology Calicut           -- Kerala
Indian Institute of Technology Gandhinagar         -- Gujarat
Indian Institute of Technology Ropar               -- Punjab
Indian Institute of Technology Patna               -- Bihar
Visvesvaraya National Institute of Technology, Nagpur -- Maharashtra
Indian Institute of Technology Mandi               -- Himachal Pradesh
School of Engineering, Tezpur University, Napaam, Tezpur -- Assam
Malaviya National Institute of Technology Jaipur   -- Rajasthan
Birla Institute of Technology, Mesra, Ranchi       -- Jharkhand
National Institute of Technology, Kurukshetra      -- Haryana
National Institute of Technology, Silchar          -- Assam
National Institute of Technology Durgapur          -- West Bengal
Motilal Nehru National Institute of Technology Allahabad -- Uttar Pradesh
Dr. B R Ambedkar National Institute of Technology, Jalandhar -- Punjab
Indian Institute of Technology Jodhpur             -- Rajasthan
Sardar Vallabhbhai National Institute of Technology, Surat -- Gujarat
National Institute of Technology Meghalaya         -- Meghalaya
Maulana Azad National Institute of Technology Bhopal -- Madhya Pradesh
Indian Institute of Information Technology Guwahati -- Assam
National Institute of Technology Raipur            -- Chhattisgarh
Punjab Engineering College, Chandigarh             -- Punjab
National Institute of Technology Agartala          -- Tripura
National Institute of Technology Goa               -- Goa
National Institute of Technology, Jamshedpur       -- Jharkhand
Pt. Dwarka Prasad Mishra Indian Institute of Information Technology, Design & Manufacture Jabalpur -- Madhya Pradesh
National Institute of Technology Patna             -- Bihar
National Institute of Technology Hamirpur          -- Himachal Pradesh
Indian Institute of Technology Tirupati            -- Andhra Pradesh
Indian Institute of Technology Palakkad            -- Kerala
Indian Institute of Technology Bhilai              -- Chhattisgarh
Indian Institute of Technology Goa                 -- Goa
Indian Institute of Technology Jammu               -- Jammu
Indian Institute of Technology Dharwad             -- Karnataka
Atal Bihari Vajpayee Indian Institute of Information Technology & Management Gwalior -- Madhya Pradesh
Indian Institute of Information Technology, Allahabad -- Uttar Pradesh
Pondicherry Engineering College, Puducherry        -- Puducherry
National Institute of Technology Puducherry        -- Puducherry
National Institute of Technology, Manipur          -- Manipur
Indian Institute of Information Technology, Design & Manufacturing, Kancheepuram -- Tamil Nadu
National Institute of Technology Arunachal Pradesh -- Arunachal Pradesh
National Institute of Technology, Srinagar         -- Jammu
National Institute of Technology Delhi             -- Delhi
National Institute of Technology, Mizoram          -- Mizoram
National Institute of Technology Nagaland          -- Nagaland
National Institute of Technology Sikkim            -- Sikkim
National Institute of Technology, Uttarakhand      -- Uttarakhand
National Institute of Technology, Andhra Pradesh   -- Andhra Pradesh
Indian Institute of Information Technology (IIIT) Pune -- Maharashtra
Indian Institute of Information Technology (IIIT)Kota, Rajasthan -- Rajasthan
Indian Institute of Information Technology (IIIT), Sri City, Chittoor -- Andhra Pradesh
Indian Institute of Information Technology(IIIT), Vadodara, Gujrat -- Gujarat
Indian Institute of Information Technology, Vadodara International Campus Diu (IIITVICD) -- Gujarat
Indian Institute of Information Technology (IIIT) Nagpur -- Maharashtra
Indian Institute of Information Technology(IIIT) Kalyani, West Bengal -- West Bengal
Indian Institute of Information Technology Lucknow -- Uttar Pradesh
Indian Institute of Information Technology(IIIT) Dharwad -- Karnataka
Indian Institute of Information Technology Bhagalpur -- Bihar
Indian Institute of Information Technology Bhopal  -- Madhya Pradesh
Indian Institute of Information Technology(IIIT) Kottayam -- Kerala
Indian Institute of Information Technology (IIIT) Ranchi -- Jharkhand
Indian Institute of Information Technology Surat   -- Gujarat
Indian Institute of Information Technology Manipur -- Manipur
Indian Institute of Information Technology Design & Manufacturing Kurnool, Andhra Pradesh -- Andhra Pradesh
Indian Institute of Information Technology Srirangam, Tiruchirappalli -- Tamil Nadu
Indian Institute of Information Technology(IIIT) Kilohrad, Sonepat, Haryana -- Haryana
Indian Institute of Information Technology, Agartala -- Tripura
Indian institute of information technology, Raichur, Karnataka -- Karnataka
Indian Institute of Information Technology(IIIT) Una, Himachal Pradesh -- Himachal Pradesh
Assam University, Silchar                          -- Assam
Gurukula Kangri Vishwavidyalaya, Haridwar          -- Uttarakhand
Indian Institute of Carpet Technology, Bhadohi     -- Uttar Pradesh
Institute of Infrastructure, Technology, Research and Management-Ahmedabad -- Gujarat
Institute of Technology, Guru Ghasidas Vishwavidyalaya (A Central University), Bilaspur, (C.G.) -- Chhattisgarh
J.K. Institute of Applied Physics & Technology, Department of Electronics & Communication, University of Allahabad- Allahabad -- Uttar Pradesh
National Institute of Electronics and Information Technology, Aurangabad (Maharashtra) -- Maharashtra
National Institute of Foundry & Forge Technology, Hatia, Ranchi -- Jharkhand
Sant Longowal Institute of Engineering and Technology -- Punjab
Mizoram University, Aizawl                         -- Mizoram
School of Planning & Architecture, Bhopal          -- Madhya Pradesh
School of Planning & Architecture, New Delhi       -- Delhi
School of Planning & Architecture: Vijayawada      -- Andhra Pradesh
Shri Mata Vaishno Devi University, Katra, Jammu & Kashmir -- Jammu
HNB Garhwal University Srinagar (Garhwal)          -- Uttarakhand
International Institute of Information Technology, Naya Raipur -- Chhattisgarh
International Institute of Information Technology, Bhubaneswar -- Odisha
Central institute of Technology Kokrajar, Assam    -- Assam
Ghani Khan Choudhary Institute of Engineering and Technology, Malda, West Bengal -- West Bengal
Central University of Rajasthan, Rajasthan         -- Rajasthan
National Institute of Food Technology Entrepreneurship and Management, Sonepat, Haryana -- Haryana
lndian Institute of Food Processing Technology, Thanjavur, Tamil Naidu. -- Tamil Nadu
North Eastern Regional Institute of Science and Technology, Nirjuli-791109 (Itanagar),Arunachal Pradesh -- Arunachal Pradesh

In [9]:
for i in df["Institute"]:
    if i not in college_sorter:
        print(i)

In [10]:
preparatory = []
for i in range(len(df["Closing Rank"])):
    if "P" in df["Closing Rank"].loc[i]:
        preparatory.append(i)
        
df_prep = df.loc[preparatory]
df_prep["Closing Rank"] = df_prep["Closing Rank"].apply(lambda x : x[:-1])
df_prep["Opening Rank"] = df_prep["Opening Rank"].apply(lambda x : x[:-1])
df_prep[["Opening Rank" , "Closing Rank"]] = df_prep[["Opening Rank" , "Closing Rank"]].apply(pd.to_numeric, errors='coerce')
df_prep

,Institute,Academic Program Name,Quota,Seat Type,Gender,Opening Rank,Closing Rank,State
2,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,OPEN (PwD),Gender-Neutral,254,254,Odisha
13,Indian Institute of Technology Bhubaneswar,Civil Engineering and M. Tech. in Structural E...,AI,OPEN (PwD),Gender-Neutral,242,242,Odisha
40,Indian Institute of Technology Bhubaneswar,"Computer Science and Engineering (4 Years, Bac...",AI,EWS (PwD),Gender-Neutral,31,31,Odisha
71,Indian Institute of Technology Bhubaneswar,"Electrical Engineering (4 Years, Bachelor of T...",AI,ST,Female-only (including Supernumerary),301,301,Odisha
74,Indian Institute of Technology Bhubaneswar,Electronics and Communication Engineering (4 Y...,AI,OPEN (PwD),Gender-Neutral,37,37,Odisha
...,...,...,...,...,...,...,...,...
2623,Indian Institute of Technology Jammu,"Mechanical Engineering (4 Years, Bachelor of T...",AI,ST,Female-only (including Supernumerary),819,819,Jammu
2633,Indian Institute of Technology Dharwad,"Computer Science and Engineering (4 Years, Bac...",AI,ST,Female-only (including Supernumerary),482,482,Karnataka
2643,Indian Institute of Technology Dharwad,"Electrical Engineering (4 Years, Bachelor of T...",AI,ST,Female-only (including Supernumerary),345,345,Karnataka
2652,Indian Institute of Technology Dharwad,"Mechanical Engineering (4 Years, Bachelor of T...",AI,ST,Gender-Neutral,89,210,Karnataka
2653,Indian Institute of Technology Dharwad,"Mechanical Engineering (4 Years, Bachelor of T...",AI,ST,Female-only (including Supernumerary),128,128,Karnataka

In [11]:
# df_prep.to_csv("Data/Extras/Preperatory_2020_dataset.csv" , index = False)

In [12]:
df.drop(preparatory , inplace = True)
df = df.reset_index(drop = True)
df

,Institute,Academic Program Name,Quota,Seat Type,Gender,Opening Rank,Closing Rank,State
0,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,OPEN,Gender-Neutral,8816,11238,Odisha
1,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,OPEN,Female-only (including Supernumerary),13312,15697,Odisha
2,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,EWS,Gender-Neutral,1579,1779,Odisha
3,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,EWS,Female-only (including Supernumerary),2655,2819,Odisha
4,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,OBC-NCL,Gender-Neutral,3057,4073,Odisha
...,...,...,...,...,...,...,...,...
8455,North Eastern Regional Institute of Science an...,"Electrical Engineering (4 Years, Bachelor of T...",AI,EWS,Gender-Neutral,9515,9515,Arunachal Pradesh
8456,North Eastern Regional Institute of Science an...,Electronics and Communication Engineering (4 Y...,AI,OPEN,Gender-Neutral,23734,23734,Arunachal Pradesh
8457,North Eastern Regional Institute of Science an...,Electronics and Communication Engineering (4 Y...,AI,EWS,Gender-Neutral,10153,10153,Arunachal Pradesh
8458,North Eastern Regional Institute of Science an...,"Mechanical Engineering (4 Years, Bachelor of T...",AI,EWS,Gender-Neutral,9547,9547,Arunachal Pradesh
8459,North Eastern Regional Institute of Science an...,"Mechanical Engineering (4 Years, Bachelor of T...",AI,OBC-NCL,Gender-Neutral,19386,19386,Arunachal Pradesh

In [13]:
df.loc[df["Institute"] == "Dr. B R Ambedkar National Institute of Technology, Jalandhar"]

,Institute,Academic Program Name,Quota,Seat Type,Gender,Opening Rank,Closing Rank,State
2321,Dr. B R Ambedkar National Institute of Technol...,"Bio Technology (4 Years, Bachelor of Technology)",HS,OPEN,Gender-Neutral,56242,81305,Punjab
2322,Dr. B R Ambedkar National Institute of Technol...,"Bio Technology (4 Years, Bachelor of Technology)",HS,OPEN,Female-only (including Supernumerary),57261,66839,Punjab
2323,Dr. B R Ambedkar National Institute of Technol...,"Bio Technology (4 Years, Bachelor of Technology)",HS,EWS,Gender-Neutral,17053,20551,Punjab
2324,Dr. B R Ambedkar National Institute of Technol...,"Bio Technology (4 Years, Bachelor of Technology)",HS,EWS,Female-only (including Supernumerary),24781,24781,Punjab
2325,Dr. B R Ambedkar National Institute of Technol...,"Bio Technology (4 Years, Bachelor of Technology)",HS,OBC-NCL,Gender-Neutral,70092,127839,Punjab
...,...,...,...,...,...,...,...,...
2541,Dr. B R Ambedkar National Institute of Technol...,"Textile Technology (4 Years, Bachelor of Techn...",OS,OBC-NCL,Female-only (including Supernumerary),15834,20482,Punjab
2542,Dr. B R Ambedkar National Institute of Technol...,"Textile Technology (4 Years, Bachelor of Techn...",OS,SC,Gender-Neutral,7888,8690,Punjab
2543,Dr. B R Ambedkar National Institute of Technol...,"Textile Technology (4 Years, Bachelor of Techn...",OS,SC,Female-only (including Supernumerary),10356,10356,Punjab
2544,Dr. B R Ambedkar National Institute of Technol...,"Textile Technology (4 Years, Bachelor of Techn...",OS,ST,Gender-Neutral,3228,3407,Punjab
2545,Dr. B R Ambedkar National Institute of Technol...,"Textile Technology (4 Years, Bachelor of Techn...",OS,ST,Female-only (including Supernumerary),4318,4318,Punjab

In [14]:
df.loc[2321]

Institute                Dr. B R Ambedkar National Institute of Technol...
Academic Program Name     Bio Technology (4 Years, Bachelor of Technology)
Quota                                                                   HS
Seat Type                                                             OPEN
Gender                                                      Gender-Neutral
Opening Rank                                                         56242
Closing Rank                                                         81305
State                                                               Punjab
Name: 2321, dtype: object

In [15]:
df_temp = df.loc[range(0 , 2321)]
df_temp

,Institute,Academic Program Name,Quota,Seat Type,Gender,Opening Rank,Closing Rank,State
0,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,OPEN,Gender-Neutral,8816,11238,Odisha
1,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,OPEN,Female-only (including Supernumerary),13312,15697,Odisha
2,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,EWS,Gender-Neutral,1579,1779,Odisha
3,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,EWS,Female-only (including Supernumerary),2655,2819,Odisha
4,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,OBC-NCL,Gender-Neutral,3057,4073,Odisha
...,...,...,...,...,...,...,...,...
2316,Indian Institute of Technology Dharwad,"Mechanical Engineering (4 Years, Bachelor of T...",AI,EWS,Female-only (including Supernumerary),3568,3568,Karnataka
2317,Indian Institute of Technology Dharwad,"Mechanical Engineering (4 Years, Bachelor of T...",AI,OBC-NCL,Gender-Neutral,2381,4472,Karnataka
2318,Indian Institute of Technology Dharwad,"Mechanical Engineering (4 Years, Bachelor of T...",AI,OBC-NCL,Female-only (including Supernumerary),7031,7538,Karnataka
2319,Indian Institute of Technology Dharwad,"Mechanical Engineering (4 Years, Bachelor of T...",AI,SC,Gender-Neutral,1998,2614,Karnataka
2320,Indian Institute of Technology Dharwad,"Mechanical Engineering (4 Years, Bachelor of T...",AI,SC,Female-only (including Supernumerary),3274,3339,Karnataka

In [16]:
df_temp[["Opening Rank" , "Closing Rank"]] = df_temp[["Opening Rank" , "Closing Rank"]].apply(pd.to_numeric, errors='coerce')

In [17]:
df_temp

,Institute,Academic Program Name,Quota,Seat Type,Gender,Opening Rank,Closing Rank,State
0,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,OPEN,Gender-Neutral,8816,11238,Odisha
1,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,OPEN,Female-only (including Supernumerary),13312,15697,Odisha
2,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,EWS,Gender-Neutral,1579,1779,Odisha
3,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,EWS,Female-only (including Supernumerary),2655,2819,Odisha
4,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,OBC-NCL,Gender-Neutral,3057,4073,Odisha
...,...,...,...,...,...,...,...,...
2316,Indian Institute of Technology Dharwad,"Mechanical Engineering (4 Years, Bachelor of T...",AI,EWS,Female-only (including Supernumerary),3568,3568,Karnataka
2317,Indian Institute of Technology Dharwad,"Mechanical Engineering (4 Years, Bachelor of T...",AI,OBC-NCL,Gender-Neutral,2381,4472,Karnataka
2318,Indian Institute of Technology Dharwad,"Mechanical Engineering (4 Years, Bachelor of T...",AI,OBC-NCL,Female-only (including Supernumerary),7031,7538,Karnataka
2319,Indian Institute of Technology Dharwad,"Mechanical Engineering (4 Years, Bachelor of T...",AI,SC,Gender-Neutral,1998,2614,Karnataka
2320,Indian Institute of Technology Dharwad,"Mechanical Engineering (4 Years, Bachelor of T...",AI,SC,Female-only (including Supernumerary),3274,3339,Karnataka

In [18]:
df_temp.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2321 entries, 0 to 2320
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Institute              2321 non-null   object
 1   Academic Program Name  2321 non-null   object
 2   Quota                  2321 non-null   object
 3   Seat Type              2321 non-null   object
 4   Gender                 2321 non-null   object
 5   Opening Rank           2321 non-null   int64
 6   Closing Rank           2321 non-null   int64
 7   State                  2321 non-null   object
dtypes: int64(2), object(6)
memory usage: 163.2+ KB

In [19]:
# df_temp.to_csv("Data/Non_Prep_Adv_2020.csv" , index = False)

In [20]:
adv_rank = int(200)
mains_rank = int(12123)
cat = "OPEN"
prepare = False
gender = "Gender-Neutral"
state = "Odisha"

In [21]:
def only_adv(prepare , adv_rank , cat , gender , state):
    
    if prepare :
        final = df_prep.loc[(df_prep["Seat Type"] == cat) & (df_prep["Gender"] == gender) & (df_prep["Closing Rank"] >= adv_rank)].sort_values(by = ["Institute"] , ascending = [college_sorter]).reset_index(drop = True) 
        
    else:
        final = df.loc[(df["Seat Type"] == cat) & (df["Gender"] == gender) & (df["Closing Rank"] >= adv_rank)].sort_values(by = ["Institute"] , ascending = [college_sorter]).reset_index(drop = True)

In [28]:
df[["Opening Rank" , "Closing Rank"]] = df[["Opening Rank" , "Closing Rank"]].apply(pd.to_numeric, errors='coerce')

In [29]:
df

,Institute,Academic Program Name,Quota,Seat Type,Gender,Opening Rank,Closing Rank,State
0,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,OPEN,Gender-Neutral,8816,11238,Odisha
1,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,OPEN,Female-only (including Supernumerary),13312,15697,Odisha
2,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,EWS,Gender-Neutral,1579,1779,Odisha
3,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,EWS,Female-only (including Supernumerary),2655,2819,Odisha
4,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,OBC-NCL,Gender-Neutral,3057,4073,Odisha
...,...,...,...,...,...,...,...,...
8455,North Eastern Regional Institute of Science an...,"Electrical Engineering (4 Years, Bachelor of T...",AI,EWS,Gender-Neutral,9515,9515,Arunachal Pradesh
8456,North Eastern Regional Institute of Science an...,Electronics and Communication Engineering (4 Y...,AI,OPEN,Gender-Neutral,23734,23734,Arunachal Pradesh
8457,North Eastern Regional Institute of Science an...,Electronics and Communication Engineering (4 Y...,AI,EWS,Gender-Neutral,10153,10153,Arunachal Pradesh
8458,North Eastern Regional Institute of Science an...,"Mechanical Engineering (4 Years, Bachelor of T...",AI,EWS,Gender-Neutral,9547,9547,Arunachal Pradesh
8459,North Eastern Regional Institute of Science an...,"Mechanical Engineering (4 Years, Bachelor of T...",AI,OBC-NCL,Gender-Neutral,19386,19386,Arunachal Pradesh

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8460 entries, 0 to 8459
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Institute              8460 non-null   object
 1   Academic Program Name  8460 non-null   object
 2   Quota                  8460 non-null   object
 3   Seat Type              8460 non-null   object
 4   Gender                 8460 non-null   object
 5   Opening Rank           8460 non-null   int64
 6   Closing Rank           8460 non-null   int64
 7   State                  8460 non-null   object
dtypes: int64(2), object(6)
memory usage: 528.9+ KB

In [33]:
df.loc[(df["Seat Type"] == cat) & (df["Gender"] == gender) & (df["Closing Rank"] >= adv_rank)].sort_values(by = ["Institute"] , ascending = [college_sorter]).reset_index(drop = True)

,Institute,Academic Program Name,Quota,Seat Type,Gender,Opening Rank,Closing Rank,State
0,"Assam University, Silchar",Electronics and Communication Engineering (4 Y...,AI,OPEN,Gender-Neutral,46584,52116,Assam
1,"Assam University, Silchar","Computer Science and Engineering (4 Years, Bac...",HS,OPEN,Gender-Neutral,69847,137482,Assam
2,"Assam University, Silchar","Computer Science and Engineering (4 Years, Bac...",AI,OPEN,Gender-Neutral,39092,46287,Assam
3,"Assam University, Silchar","Agricultural Engineering (4 Years, Bachelor of...",HS,OPEN,Gender-Neutral,186636,257783,Assam
4,"Assam University, Silchar","Agricultural Engineering (4 Years, Bachelor of...",AI,OPEN,Gender-Neutral,61479,65371,Assam
...,...,...,...,...,...,...,...,...
969,"Visvesvaraya National Institute of Technology,...","Architecture (5 Years, Bachelor of Architecture)",OS,OPEN,Gender-Neutral,569,1183,Maharashtra
970,"Visvesvaraya National Institute of Technology,...","Architecture (5 Years, Bachelor of Architecture)",HS,OPEN,Gender-Neutral,448,926,Maharashtra
971,"Visvesvaraya National Institute of Technology,...",Electronics and Communication Engineering (4 Y...,HS,OPEN,Gender-Neutral,6570,9820,Maharashtra
972,"Visvesvaraya National Institute of Technology,...","Chemical Engineering (4 Years, Bachelor of Tec...",OS,OPEN,Gender-Neutral,20858,26802,Maharashtra
973,lndian Institute of Food Processing Technology...,"Food Technology (4 Years, Bachelor of Technology)",AI,OPEN,Gender-Neutral,39832,63112,Tamil Nadu